site_name: WaterHackweek Learning Resources
repo_url: https://github.com/waterhackweek/learning-resources

nav:
  - Overview:
    - Introduction: index.md
    - Code of Conduct: conduct.md
    - Diversity Statement: diversityMethods.md
    - Vocabulary and Acronyms: VocabAcronyms2020.md
  - Logistics: 
    - logistics/overview.md
    - schedule.md
    - Getting Help: logistics/getting_help.md
  - Pre-event Preparation:
    - Git: prep/git.md
    - GitHub: prep/github.md
    - Jupyter and the Hub: prep/jupyterhub.md
    - HydroShare: hydroshare.md
    - Binder: binder.md
    # - Github: github.md
    # - Conda: conda.md
    # - Conda, Python, R: prep/conda.md
    # - Python Requirements: preweek/python.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    # - Data Access in Python: tutorials/github.md
    - Numpy: numpy.md
    - Pandas: pandas.md
    - GEE Access and Javascript Tips: gee_javascript.md
  - Projects: 
    - Project Roles and Responsibilities: project.md
  - Scientific Methods: reproducibility101.md
  - How to Contribute: howtocontribute.md

theme: 
  name: readthedocs
  collapse_by_default: false
  highlightjs: true

plugins:
  - search
  - markdownextradata

markdown_extensions:
  - admonition

extra_css:
  - extra.css

extra:
  hackweek:
    name: Waterhackweek
    web_url: https://waterhackweek.github.io
    slack_url: https://waterhackweek.slack.com
    github_org_url: https://github.com/waterhackweek
    jupyterhub_url: https://jupyterhub.cuahsi.org
    cyberseminar_url: https://www.cuahsi.org/education/cyberseminars/waterhackweek-cyberseminar-series
    admin_contact: Owen Freed
    email: fwi@uw.edu
