site_name: hackweek preliminary tutorials
nav:
    - Home: index.md
    - Lesson 1: github.md
    - Lesson 2: jupyterhub.md
    - Lesson 3: conda.md
    #- Lesson 4: earthdata.md
    - Lesson 4: numpy.md
    - Lesson 5: pandas.md
theme: 
    name: readthedocs
    highlightjs: true
plugins:
    - search
    - markdownextradata
extra:
  hackweek:
    name: Waterhackweek
    web_url: https://waterhackweek.github.io
    slack_url: https://waterhackweek.slack.com
    github_org_url: https://github.com/waterhackweek
    pangeo_url: https://aws-uswest2.pangeo.io
    admin_contact: Jane Koh
markdown_extensions:
  - admonition
repo_url: https://github.com/waterhackweek/learning-resources
