site_name: Waterhackweek Learning Resources
repo_url: https://github.com/waterhackweek/learning-resources

nav:
  - Overview:
    - Introduction: index.md
    - Code of Conduct: conduct.md
    - Diversity Statement: diversityMethods.md
  - Logistics: 
    - Overview and Schedule: logistics/overview.md
    - Getting Help: logistics/getting_help.md
  - Pre-event Preparation:
    - Git: prep/git.md
    - GitHub: prep/github.md
    - Jupyter and JupyterHub: prep/jupyterhub.md
    - Python Ecosystem: prep/pythonecosystem.md
    # - Python and conda
    # - HydroShare: hydroshare.md
    # - Binder: binder.md
    # - Conda: conda.md
    # - Conda, Python, R: prep/conda.md
    # - Python Requirements: preweek/python.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    - Numpy: numpy.md
    - Pandas: pandas.md
    # - GEE Access and Javascript Tips: gee_javascript.md
  - Projects:
    - Roles and Responsibilities: project.md
  - Reference:
    - Vocabulary and Acronyms: VocabAcronyms2020.md
    - Scientific Methods: reproducibility101.md
    - How to Contribute: howtocontribute.md

theme: 
  name: readthedocs
  collapse_by_default: false
  highlightjs: true

plugins:
  - search
  - markdownextradata

markdown_extensions:
  - admonition

extra_css:
  - extra.css

extra:
  hackweek:
    name: Waterhackweek
    prefix: whw
    currentprefix: whw20
    web_url: https://waterhackweek.github.io
    slack_url: https://waterhackweek.slack.com
    github_org_url: https://github.com/waterhackweek
    jupyterhub_url: https://jupyterhub.cuahsi.org
    cyberseminar_url: https://www.cuahsi.org/education/cyberseminars/waterhackweek-cyberseminar-series
    admin_contact: Owen Freed
    email: waterhackweek@uw.edu
